#!/bin/bash

[[ -z "$1" ]] && echo "usage: close-window WINDOW TITLE" && exit 1

readarray -t window < <(wmctrl -l 2>/dev/null | grep "$*" | cut -d " " -f 1)
echo "[${window[@]}]"
[[ "${#window[@]}" -ge 1 ]] && wmctrl -i -c "${window[@]}"
