#!/bin/sh

URL='https://wttr.in/{${CITY}}'

if [ "$1" == "-f" ]
then
    shift
    default="Porto_Alegre"
else
    export FORMAT=${FORMAT:-4}
    default="Porto_Alegre,SBPA"
    URL='https://wttr.in/{${CITY}}?format=${FORMAT}'
fi

export CITY=${*:-${CITY:-${default}}}

curl "$(echo ${URL} | envsubst)"

# curl "${URL}"
